# Generated by Django 3.1.4 on 2020-12-04 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchaseList',
            fields=[
                ('plserial', models.AutoField(primary_key=True, serialize=False)),
                ('Qty', models.IntegerField(default=0)),
                ('reqDate', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('closeDate', models.DateField(blank=True, null=True)),
                ('parttNumber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.partnumber')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
