# Generated by Django 3.1.4 on 2020-12-17 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ccnlist',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='ccnlist',
            name='partNumber',
        ),
        migrations.RemoveField(
            model_name='ccnlist',
            name='serialNumber',
        ),
        migrations.AddField(
            model_name='ccnlist',
            name='endp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.endproduct'),
        ),
        migrations.AddField(
            model_name='endproduct',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.customer'),
        ),
    ]
