# Generated by Django 3.0.3 on 2020-09-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnumber',
            name='buylink',
            field=models.CharField(blank=True, help_text='input the purchasing link', max_length=200),
        ),
    ]
