# Generated by Django 3.1.1 on 2022-07-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomelement',
            name='replacePN',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
