# Generated by Django 3.1.4 on 2021-01-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnumber',
            name='software',
        ),
        migrations.AddField(
            model_name='endproduct',
            name='software',
            field=models.ManyToManyField(blank=True, to='erp.software'),
        ),
    ]
