# Generated by Django 3.0.3 on 2020-09-17 07:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erp', '0002_partnumber_buylink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnumber',
            name='id',
        ),
        migrations.RemoveField(
            model_name='partnumber',
            name='price',
        ),
        migrations.RemoveField(
            model_name='partnumber',
            name='qty',
        ),
        migrations.AddField(
            model_name='partnumber',
            name='Pid',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='partnumber',
            name='category',
            field=models.CharField(choices=[('LDO', 'LDO'), ('ADC', 'ADC'), ('Other', 'Other')], default='Other', max_length=15),
        ),
        migrations.AddField(
            model_name='partnumber',
            name='date',
            field=models.DateField(default=datetime.date(2020, 9, 17)),
        ),
        migrations.AddField(
            model_name='partnumber',
            name='discription',
            field=models.TextField(blank=True, help_text='must input key paramter discription here', null=True),
        ),
        migrations.AddField(
            model_name='partnumber',
            name='level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partnumber',
            name='location',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='changeQty',
            fields=[
                ('Qid', models.AutoField(primary_key=True, serialize=False)),
                ('addQty', models.IntegerField()),
                ('date', models.DateField()),
                ('reason', models.CharField(choices=[('PO', 'purchasing'), ('DI', 'discard'), ('MP', 'production'), ('SA', 'sell out')], max_length=2)),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BomList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('busr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='erp.partNumber')),
            ],
        ),
        migrations.CreateModel(
            name='BomElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitQty', models.IntegerField(default=1)),
                ('BEid', models.IntegerField()),
                ('unitPrice', models.FloatField()),
                ('BomList', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.BomList')),
            ],
        ),
    ]
