# Generated by Django 3.1.4 on 2020-12-04 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_purchaselist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaselist',
            old_name='parttNumber',
            new_name='partNumber',
        ),
    ]
