# Generated by Django 3.1.4 on 2021-01-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_auto_20210105_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnumber',
            name='software',
            field=models.ManyToManyField(blank=True, to='erp.software'),
        ),
    ]
