# Generated by Django 3.1.4 on 2021-01-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_partnumber_software'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
