# Generated by Django 3.0.3 on 2020-09-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_auto_20200917_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnumber',
            name='Pid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
