# Generated by Django 3.1.4 on 2020-12-14 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_auto_20201204_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('add', models.CharField(blank=True, max_length=60, null=True)),
                ('vax', models.CharField(blank=True, max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mpList',
            fields=[
                ('mpSerial', models.AutoField(primary_key=True, serialize=False)),
                ('Qty', models.IntegerField(default=0)),
                ('reqDate', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('closeDate', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.customer')),
                ('partNumber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.partnumber')),
            ],
        ),
        migrations.CreateModel(
            name='ccnList',
            fields=[
                ('ccnSerial', models.AutoField(primary_key=True, serialize=False)),
                ('serialNumber', models.CharField(max_length=15)),
                ('reqDate', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('rootCause', models.TextField(verbose_name=models.TextField(blank=True, help_text='input the rootCause of failure', null=True))),
                ('closeDate', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.customer')),
                ('partNumber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.partnumber')),
            ],
        ),
    ]
