# Generated by Django 3.1.4 on 2020-12-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_ccnlist_closeeng'),
    ]

    operations = [
        migrations.CreateModel(
            name='software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('discription', models.CharField(max_length=100)),
                ('history', models.TextField(blank=True, help_text='reversion history', null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ccnlist',
            name='failure',
            field=models.TextField(blank=True, help_text='input failure phenomenon', null=True),
        ),
        migrations.AlterField(
            model_name='ccnlist',
            name='rootCause',
            field=models.TextField(blank=True, help_text='input the rootCause of failure', null=True),
        ),
        migrations.AddField(
            model_name='partnote',
            name='software',
            field=models.ManyToManyField(blank=True, null=True, to='erp.software'),
        ),
    ]
