# Generated by Django 3.0.3 on 2020-09-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_auto_20200918_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnumber',
            name='category',
            field=models.CharField(max_length=10),
        ),
    ]
