# Generated by Django 3.0.3 on 2020-09-19 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erp', '0008_auto_20200918_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changeqty',
            name='usr',
        ),
        migrations.RemoveField(
            model_name='bomelement',
            name='BEid',
        ),
        migrations.RemoveField(
            model_name='bomelement',
            name='BomList',
        ),
        migrations.RemoveField(
            model_name='bomelement',
            name='unitPrice',
        ),
        migrations.AddField(
            model_name='bomelement',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bomelement',
            name='partNumber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.partNumber'),
        ),
        migrations.AddField(
            model_name='bomelement',
            name='usr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='partnumber',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='BomList',
        ),
        migrations.DeleteModel(
            name='changeQty',
        ),
    ]
