# Generated by Django 3.0.3 on 2020-09-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_auto_20200919_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomelement',
            name='Pid',
            field=models.IntegerField(default=-1),
        ),
    ]
