# Generated by Django 3.0.3 on 2020-09-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_bomelement_pid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bomelement',
            old_name='partNumber',
            new_name='product',
        ),
        migrations.AddField(
            model_name='bomelement',
            name='partPN',
            field=models.CharField(default='none', max_length=80),
        ),
    ]
