# Generated by Django 3.0.3 on 2020-09-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_auto_20200921_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomelement',
            name='schPN',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
