# Generated by Django 3.0.3 on 2020-09-21 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_bomelement_schpn'),
    ]

    operations = [
        migrations.CreateModel(
            name='partNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=15, null=True)),
                ('package', models.CharField(blank=True, max_length=15, null=True)),
                ('param1', models.CharField(blank=True, max_length=15, null=True)),
                ('param2', models.CharField(blank=True, max_length=15, null=True)),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.partNumber')),
            ],
        ),
    ]
