# Generated by Django 3.0.3 on 2020-09-21 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0015_pnqty_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pnqty',
            old_name='qtyChange',
            new_name='failedQty',
        ),
        migrations.AddField(
            model_name='pnqty',
            name='passedChange',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pnqty',
            name='untestedQty',
            field=models.IntegerField(default=0),
        ),
    ]
