# Generated by Django 3.0.3 on 2020-09-21 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0016_auto_20200921_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pnqty',
            old_name='passedChange',
            new_name='passedChangeQty',
        ),
    ]
