# Generated by Django 3.0.3 on 2020-09-22 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0017_auto_20200921_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pnqty',
            old_name='passedChangeQty',
            new_name='passedQty',
        ),
    ]
