# Generated by Django 3.0.3 on 2020-09-22 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0018_auto_20200922_0240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pnqty',
            old_name='usr',
            new_name='user',
        ),
    ]
