# Generated by Django 3.0.3 on 2020-09-22 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0019_auto_20200922_0242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eleprice',
            old_name='usr',
            new_name='user',
        ),
    ]
