# Generated by Django 3.0.3 on 2020-09-22 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0021_pnqty_discardqty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pnqty',
            old_name='passedQty',
            new_name='Qty',
        ),
        migrations.RemoveField(
            model_name='pnqty',
            name='discardQty',
        ),
        migrations.RemoveField(
            model_name='pnqty',
            name='failedQty',
        ),
        migrations.RemoveField(
            model_name='pnqty',
            name='untestedQty',
        ),
    ]
