# Generated by Django 3.0.3 on 2020-09-22 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0023_planerelement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bomelement',
            old_name='usr',
            new_name='user',
        ),
    ]
