# Generated by Django 3.0.3 on 2020-09-23 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0024_auto_20200922_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bomelement',
            name='Pid',
        ),
        migrations.RemoveField(
            model_name='bomelement',
            name='partPN',
        ),
        migrations.AddField(
            model_name='bomelement',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='element', to='erp.partNumber'),
        ),
    ]
