# Generated by Django 3.0.3 on 2020-10-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0025_auto_20200923_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnote',
            old_name='param2',
            new_name='addVendor',
        ),
        migrations.AddField(
            model_name='partnote',
            name='addBuylink',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pnqty',
            name='untestQty',
            field=models.IntegerField(default=0),
        ),
    ]
