# Generated by Django 3.0.3 on 2020-10-02 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0026_auto_20201001_0855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnote',
            old_name='addVendor',
            new_name='param2',
        ),
    ]
