# Generated by Django 3.0.3 on 2020-10-06 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0027_auto_20201002_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomelement',
            name='bomserial',
            field=models.IntegerField(default=0),
        ),
    ]
