# Generated by Django 3.0.3 on 2020-10-06 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0028_bomelement_bomserial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bomDefine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bomserial', models.IntegerField(default=0)),
                ('discription', models.CharField(blank=True, max_length=100, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.partNumber')),
            ],
        ),
    ]
